version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.sbt" }}
            - v1-dependencies-
      - run: sbt clean update scalafmtCheckAll scalafmtSbtCheck
      - save_cache:
          paths:
            - ~/.ivy2
          key: v1-dependencies--{{ checksum "build.sbt" }}
      - run: sbt compile coverage test:test coverageReport
      - run: bash <(curl -s https://codecov.io/bash)


